# Generated by Django 4.0.5 on 2022-06-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebapp', '0002_neighborhood_user_image_user_name_post_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
