# Generated by Django 4.0.5 on 2022-06-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebapp', '0004_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
