# Generated by Django 4.0.5 on 2022-06-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebapp', '0005_alter_neighborhood_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='pics/'),
        ),
    ]
