# Generated by Django 4.0.5 on 2022-06-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebapp', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jng', upload_to='pics/'),
        ),
    ]
